# Generated by Django 5.0.4 on 2024-06-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_generator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='content',
        ),
        migrations.AddField(
            model_name='posts',
            name='content_url',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
